---
- s3_bucket:
    resource: "AWS::S3::Bucket"
    documentation:
      short_description: Create and manage S3 buckets
      description:
        - Create and manage S3 buckets.
- logs_log_group:
    resource: "AWS::Logs::LogGroup"
    documentation:
      short_description: Create and manage log groups
      description:
        - Create and manage log groups.
- iam_role:
    resource: "AWS::IAM::Role"
    documentation:
      short_description: Create and manage roles
      description:
        - Creates and manages new roles for your AWS account.
- backup_backup_vault:
    resource: "AWS::Backup::BackupVault"
    documentation:
      short_description: Create and manage logical containers where backups are stored
      description:
        - Creates and manages logical containers where backups are stored.
- backup_framework:
    resource: "AWS::Backup::Framework"
    documentation:
      short_description: Create and manage frameworks with one or more controls
      description:
        - Creates and manages frameworks with one or more controls.
- backup_report_plan:
    resource: "AWS::Backup::ReportPlan"
    documentation:
      short_description: Create and manage report plans
      description:
        - Creates and manages report plans.
- eks_cluster:
    resource: "AWS::EKS::Cluster"
    documentation:
      short_description: Create and manages Amazon EKS control planes
      description:
        - Create and manage Amazon EKS control planes.
- lambda_code_signing_config:
    resource: "AWS::Lambda::CodeSigningConfig"
    documentation:
      short_description: Code signing for AWS Lambda
      description:
        - Creates and manage code signing for AWS Lambda.
- lambda_event_source_mapping:
    resource: "AWS::Lambda::EventSourceMapping"
    documentation:
      short_description: Create a mapping between an event source and an AWS Lambda function
      description:
        - Create a mapping between an event source and an AWS Lambda function.
- lambda_function:
    resource: "AWS::Lambda::Function"
    documentation:
      short_description: Create and manage Lambda functions
      description:
        - Creates and manage Lambda functions.
- logs_query_definition:
    resource: "AWS::Logs::QueryDefinition"
    documentation:
      short_description: Create and manage query definitions
      description:
        - Creates and manage query definitions for CloudWatch Logs Insights.
- logs_resource_policy:
    resource: "AWS::Logs::ResourcePolicy"
    documentation:
      short_description: Create and manage resource policies
      description:
        - Creates and manage resource policies that allows other AWS services to put log events to the account.
- rds_db_proxy:
    resource: "AWS::RDS::DBProxy"
    documentation:
      short_description: Create and manage DB proxies
      description:
        - Creates and manage DB proxies.
- redshift_cluster:
    resource: "AWS::Redshift::Cluster"
    documentation:
      short_description: Create and manage clusters
      description:
        - Creates and manage clusters.
- redshift_event_subscription:
    resource: "AWS::Redshift::EventSubscription"
    documentation:
      short_description: Create and manage Amazon Redshift event notification subscriptions
      description:
        - Creates and manage Amazon Redshift event notification subscriptions.
- s3_access_point:
    resource: "AWS::S3::AccessPoint"
    documentation:
      short_description: Create and manage Amazon S3 access points to use to access S3 buckets
      description:
        - Create and manage Amazon S3 access points to use to access S3 buckets.
- s3_multi_region_access_point:
    resource: "AWS::S3::MultiRegionAccessPoint"
    documentation:
      short_description: Create and manage Amazon S3 Multi-Region Access Points
      description:
        - Create and manage Amazon S3 Multi-Region Access Points.
- s3_multi_region_access_point_policy:
    resource: "AWS::S3::MultiRegionAccessPointPolicy"
    documentation:
      short_description: Manage Amazon S3 access policies
      description:
        - Applie and manage Amazon S3 access policies to an Amazon S3 Multi-Region Access Points.
- s3objectlambda_access_point:
    resource: "AWS::S3ObjectLambda::AccessPoint"
    documentation:
      short_description: Create and manage Object Lambda Access Points used to access S3 buckets
      description:
        - Create and manage Object Lambda Access Points used to access S3 buckets.
- s3objectlambda_access_point_policy:
    resource: "AWS::S3ObjectLambda::AccessPointPolicy"
    documentation:
      short_description: Specifies the Object Lambda Access Point resource policy document
      description:
        - Create and manage Object Lambda Access Point resource policy document.
# 0.2.0
- eks_fargate_profile:
    resource: "AWS::EKS::FargateProfile"
    documentation:
      short_description: Creates and manage AWS Fargate profiles
      description:
        - Creates and manage AWS Fargate profiles for your Amazon EKS cluster.
        - You must have at least one Fargate profile in a cluster to be able to run pods on Fargate.
- dynamodb_global_table:
    resource: "AWS::DynamoDB::GlobalTable"
    documentation:
      short_description: Creates and manages a Version 2019.11.21 global table
      description:
        - Creates and manages a Version 2019.11.21 global table.
        - This resource cannot be used to create or manage a Version 2017.11.29 global table.
- eks_addon:
    resource: "AWS::EKS::Addon"
    documentation:
      short_description: Creates and manages Amazon EKS add-ons
      description:
        - Creates and manages Amazon EKS add-ons.
        - Amazon EKS add-ons require clusters running version 1.18 or later because Amazon EKS add-ons rely on the Server-side Apply Kubernetes feature, which is only available in Kubernetes 1.18 and later.
        - For more information see U(https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html).
- iam_server_certificate:
    resource: "AWS::IAM::ServerCertificate"
    documentation:
      short_description: Uploads and manages a server certificate entity for the AWS account
      description:
        - Uploads and manages a server certificate entity for the AWS account.
- kms_alias:
    resource: "AWS::KMS::Alias"
    documentation:
      short_description: Specifies a display name for a KMS key.
      description:
        - Specifies a display name for a KMS key.
- kms_replica_key:
    resource: "AWS::KMS::ReplicaKey"
    documentation:
      short_description: Creates and manages a multi-Region replica key that is based on a multi-Region primary key
      description:
        - Creates andn manages a multi-Region replica key that is based on a multi-Region primary key.
- rds_db_proxy_endpoint:
    resource: "AWS::RDS::DBProxyEndpoint"
    documentation:
      short_description: Creates and manages a DB proxy endpoint
      description:
        - Creates and manages a DB proxy endpoint.
        - You can use custom proxy endpoints to access a proxy through a different VPC than the proxy's default VPC.
- redshift_endpoint_access:
    resource: "AWS::Redshift::EndpointAccess"
    documentation:
      short_description: Creates and manages Redshift-managed VPC endpoint
      description:
        - Creates and manages a Redshift-managed VPC endpoint.
- redshift_endpoint_authorization:
    resource: "AWS::Redshift::EndpointAuthorization"
    documentation:
      short_description: Describes an endpoint authorization for authorizing Redshift-managed VPC endpoint access to a cluster across AWS accounts.
      description:
        - Describes an endpoint authorization for authorizing Redshift-managed VPC endpoint access to a cluster across AWS accounts.
- redshift_scheduled_action:
    resource: "AWS::Redshift::ScheduledAction"
    documentation:
      short_description: Creates and manages a scheduled action
      description:
        - Creates and manages a scheduled action.
        - A scheduled action contains a schedule and an Amazon Redshift API action.
        - For example, you can create a schedule of when to run the ResizeCluster API operation.
- route53_dnssec:
    resource: "AWS::Route53::DNSSEC"
    documentation:
      short_description: Is used to enable DNSSEC signing in a hosted zone
      description:
        - Is used to enable DNSSEC signing in a hosted zone.
- route53_key_signing_key:
    resource: "AWS::Route53::KeySigningKey"
    documentation:
      short_description: Creates a new key-signing key (KSK) in a hosted zone
      description:
        - Creates a new key-signing key (KSK) in a hosted zone.
- cloudtrail_trail:
    resource: "AWS::CloudTrail::Trail"
    documentation:
      short_description: Creates and manages a trail that specifies the settings for delivery of log data to an Amazon S3 bucket.
      description:
        - Creates and manages a trail that specifies the settings for delivery of log data to an Amazon S3 bucket.
- cloudtrail_event_data_store:
    resource: "AWS::CloudTrail::EventDataStore"
    documentation:
      short_description: Creates and manages a new event data store
      description:
        - Creates and manages a new event data store.
- cloudwatch_composite_alarm:
    resource: "AWS::CloudWatch::CompositeAlarm"
    documentation:
      short_description: Creates and manages a composite alarm
      description:
        - Creates and manages a composite alarm.
        - When you create a composite alarm, you specify a rule expression for the alarm that takes into account the alarm states of other alarms that you have created.
        - The composite alarm goes into ALARM state only if all conditions of the rule are met.
- cloudwatch_metric_stream:
    resource: "AWS::CloudWatch::MetricStream"
    documentation:
      short_description: Creates and manages a metric stream
      description:
        - Creates and manages a metric stream.
        - Metrics streams can automatically stream CloudWatch metrics to AWS destinations including Amazon S3 and to many third-party solutions.
        - For more information, see U(https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Metric-Streams.html).
